# To apply this file, from csh or tcsh, run
# source cshrc
#
#
# You should be sure to set this in your cshrc to get to this var
#setenv SDS /disk/kea/SDS

# We want this to be the path
#setenv PATH /disk/kea/SDS/syst/ext/bin:$PATH

rehash

